version: "3.8"
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=Proyecto_U1_G1
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Datos de PostgreSQL
      - postgres_backups:/backups  # Almacén de respaldos

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "80:80"
    depends_on:
      - postgres

  web:
    build: .  # Usa el Dockerfile en el directorio actual
    volumes:
      - ./src:/var/www/html  # Montar tu proyecto PHP
    ports:
      - "8080:80"  # Cambia el puerto del host a 8080
    depends_on:
      - postgres

volumes:
  postgres_data:
  postgres_backups:
